#!/usr/bin/env bash

function command_exists() {
  type -P -f "$1" >/dev/null 2>&1
}

## sudo
alias sudo='sudo '
alias _='sudo'
alias sued='sudo --edit'
alias please='sudo $(fc -ln -1)'
alias plz='please'

## cd
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../..'
alias .5='cd ../../../..'
alias .6='cd ../../../../..'
alias home='cd ${HOME}'
alias dl='cd ${HOME}/Downloads'
alias dt='cd ${HOME}/Desktop'
alias c='cd ${CODE_DIR}'
alias bd='cd "$OLDPWD"'

## ls
if command_exists 'exa'; then
  alias exa='exa --classify --group-directories-first --icons --header --time-style=long-iso --color-scale --git'
  alias ls='exa'
  alias l='exa'
  alias ll='exa --long'
  alias la='exa --all'
  alias lla='exa --long --all'
  alias llx='exa --long --sort=extension'
  alias llax='exa --long --all --sort=extension'
  alias lls='exa --long --sort=size'
  alias llas='exa --long --all --sort=size'
  alias llc='exa --long --sort=mod'
  alias llac='exa --long --all --sort=mod'
  alias llr='exa --long --recurse'
  alias llar='exa --long --all --recurse'
  alias tree='exa --long --tree'
else
  alias ls="ls -hF --color --group-directories-first"
  alias l='ls'
  alias ll='ls -l'
  alias la='ls -A'
  alias lla='ls -Al'
  alias llx='ls -l -XB' # sort by extension
  alias llax='ls -Al -XB'
  alias lls='ls -l -lSr' # sort by size, biggest last
  alias llas='ls -Al -lSr'
  alias llc='ls -l -tcr' # sort by and show change time, most recent last
  alias llac='ls -Al -tcr'
  alias llr='ls -l -R' # recursive ls
  alias llar='ls -Al -R'
fi

## cp, mv, rm, mkdir
alias mkdir='mkdir -pv'
alias cp='cp -iv'
alias mv='mv -iv'
if command_exists 'safe-rm'; then
  alias rm='safe-rm -iv'
else
  alias rm='rm -iv'
fi

## trash
alias trp='trash-put'
alias tre='trash-empty'
alias trl='trash-list'
alias trr='trash-restore'
alias trm='trash-rm'

## chown, chmod, chgrp
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

## grep
alias grep="grep --exclude-dir='.*' --colour=auto"
alias egrep='grep -E'
alias fgrep='grep -F'

## tar
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

## ps
alias psa='ps aux'
alias psaf='ps auxf'

## editors
alias e='edit'
alias k='kate'
alias m='micro'
alias n='nano'

## misc - shorter alias
alias g='git'
alias o='xdg-open'
alias q='exit'
alias h='history'
alias t='tldr'
alias hh='hstr'
alias ms='manswitch'
alias cls='clear'
alias pager='${PAGER}'

## misc - replace commands
if command_exists 'riff'; then
  alias diff='riff'
fi
if command_exists 'type'; then
  alias which='type -a'
fi

## misc - adds flags
alias du='du -ckh'
alias df='df -kTh -x squashfs'
alias free='free -mt'
alias br='br -dhp'
alias ln='ln -v'
alias jobs='jobs -l'
alias tree='tree -Cugph'
alias shfmt='shfmt --indent 2 --case-indent'

## misc - other
alias du1='du --max-depth=1'
alias bs='br --sizes'
alias brc='source ${HOME}/.bashrc'
