#!/usr/bin/env bash

function command_exists() {
  type -P -f "$1" >/dev/null 2>&1
}

alias sudo='sudo '
alias _='sudo'
alias sued='sudo --edit'
alias please='sudo $(fc -ln -1)'
alias plz='please'

if command_exists 'exa'; then
  alias exa='exa --classify --group-directories-first --icons --header --time-style=long-iso --color-scale --git'
  alias ls='exa'
  alias l='exa'
  alias ll='exa --long'
  alias la='exa --all'
  alias lla='exa --long --all'
  alias llx='exa --long --sort=extension'
  alias llax='exa --long --all --sort=extension'
  alias lls='exa --long --sort=size'
  alias llas='exa --long --all --sort=size'
  alias llc='exa --long --sort=mod'
  alias llac='exa --long --all --sort=mod'
  alias llr='exa --long --recurse'
  alias llar='exa --long --all --recurse'
  alias tree='exa --long --tree'
else
  alias ls="ls -hF --color --group-directories-first"
  alias l='ls'
  alias ll='ls -l'
  alias la='ls -A'
  alias lla='ls -Al'
  alias llx='ls -l -XB' # sort by extension
  alias llax='ls -Al -XB'
  alias lls='ls -l -lSr' # sort by size, biggest last
  alias llas='ls -Al -lSr'
  alias llc='ls -l -tcr' # sort by and show change time, most recent last
  alias llac='ls -Al -tcr'
  alias llr='ls -l -R' # recursive ls
  alias llar='ls -Al -R'
fi

alias mkdir='mkdir -pv'
alias cp='cp -iv'
alias mv='mv -iv'
if command_exists 'safe-rm'; then
  alias rm='safe-rm -iv'
else
  alias rm='rm -iv'
fi
alias trp='trash-put'
alias tre='trash-empty'
alias trl='trash-list'
alias trr='trash-restore'
alias trm='trash-rm'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

alias rsync-bak='rsync -ahEP --stats'

alias e='edit'
alias k='kate'
alias m='micro'
alias nano='nano -c'
alias n='nano'
alias x='xdg-open'
if command_exists 'nvim'; then
  alias vim='nvim'
  alias v='nvim'
elif command_exists 'vim'; then
  alias v='vim'
else
  alias v='vi'
fi

alias grep='grep --exclude-dir=.idea --exclude-dir=.git --colour=auto'
alias egrep='grep -E'
alias fgrep='grep -F'
alias rg='rg --sort path'

alias du='du -ckh'
alias du1='du --max-depth=1'
alias df='df -kTh -x squashfs'
alias free='free -mt'

alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../..'
alias .5='cd ../../../..'
alias .6='cd ../../../../..'
alias home='cd ${HOME}'
alias dl='cd ${HOME}/Downloads'
alias dt='cd ${HOME}/Desktop'
alias c='cd ${CODE_DIR}'
alias bd='cd "$OLDPWD"'

alias tarc="tar -cvzf"
alias tarx="tar -xf"

alias br='br -dhp'
alias bs='br --sizes'

alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection

alias g='git'

if command_exists 'riff'; then
  alias diff='riff'
fi

alias copy='xsel -ib'
alias paste='xsel -ob'
alias cwd='pwd | tr -d "\r\n" | copy'
alias shrug='echo -n "¯\_(ツ)_/¯" | copy'

alias psa='ps aux'
alias psaf='ps auxf'
alias psgrep='ps aux | grep -v grep | grep -i -e VSZ -e'

alias rebootsafe='sudo shutdown -r now'
alias rebootforce='sudo shutdown -r -n now'

alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

alias ln='ln -v'
alias jobs='jobs -l'
alias map='xargs -P"$(grep -c ^processor /proc/cpuinfo)" -n1'
alias which='type -a'
alias cls='clear'
alias q='exit'
alias h='history'
alias file-extensions='find . -type f | sed -n "s/..*\.//p" | sort | uniq -c | sort -nr'
alias file-counts='du -a | cut -d/ -f2 | sort | uniq -c | sort -nr'
alias pager='${PAGER}'
alias t='tldr'
alias tree='tree -Cugph'
# use like so: sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias brc='source ${HOME}/.bashrc'
alias sdf='${CODE_DIR}/dotfiles-and-scripts/bin/sync-dotfiles-and-scripts && brc'
alias coredumps='journalctl | command grep -F "dumped core"'
alias colortest='msgcat --color=test'
alias flac2v0='flac2mp3.pl --quiet --lameargs="-V0 --noreplaygain --nohist --quiet" --processes="$(nproc)" . .'
alias compress-pdf='gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH -sOutputFile=compressed_PDF_file.pdf'
alias da='date "+%Y-%m-%d %A %T %Z"'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias update-fc='sudo fc-cache -fv'
alias shfmt='shfmt --indent 2 --case-indent'
alias hh='hstr'
