#!/usr/bin/env bash

function command_exists() {
  type -P -f "$1" >/dev/null 2>&1
}

export TIMEFORMAT=$'\nreal %3R\tuser %3U\tsys %3S\tpcpu %P\n'

export HISTCONTROL='ignorespace:ignoredups'
export HISTIGNORE='ls:ll:lla:pwd:bg:fg:history:h'
export HISTSIZE='100000'
export HISTFILESIZE="${HISTSIZE}"
export HISTTIMEFORMAT='%F %T%t'
export HISTFILE="${HOME}/.bash_history"

if command_exists 'moar'; then
  export PAGER='moar'
else
  export PAGER='less -Fi'
fi
export MANPAGER="${PAGER}"

LESS_TERMCAP_mb=$(tput -T ansi blink) # start blink
LESS_TERMCAP_md=$(tput -T ansi setaf 2 ; tput -T ansi bold) # start bold
LESS_TERMCAP_me=$(tput -T ansi sgr0)  # turn off bold, blink and underline
LESS_TERMCAP_so=$(tput -T ansi smso)  # start standout (reverse video)
LESS_TERMCAP_se=$(tput -T ansi rmso)  # stop standout
LESS_TERMCAP_us=$(tput -T ansi smul)  # start underline
LESS_TERMCAP_ue=$(tput -T ansi rmul)  # stop underline
export LESS_TERMCAP_mb
export LESS_TERMCAP_md
export LESS_TERMCAP_me
export LESS_TERMCAP_se
export LESS_TERMCAP_so
export LESS_TERMCAP_ue
export LESS_TERMCAP_us

if command_exists 'micro'; then
  export EDITOR='micro'
elif command_exist 'nano'; then
  export EDITOR='nano'
elif command_exists 'nvim'; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi
export VISUAL="${EDITOR}"

export HIGHLIGHT_OPTIONS='-O ansi --force'
export CODE_DIR="${HOME}/Code"
export SDKMAN_DIR="${HOME}/.sdkman"
export GOPATH="${HOME}/.go"
export WTTR_CITY='Atlanta'

export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/rc"
