#!/usr/bin/env bash

## personal
export CODE_DIR="${HOME}/Code"
export WTTR_CITY='Atlanta'

## editor/visual
if executable_exists 'micro'; then
  export EDITOR='micro'
elif executable_exists 'nano'; then
  export EDITOR='nano'
elif executable_exists 'nvim'; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi
export VISUAL="${EDITOR}"

## pager/manpager
if executable_exists 'moar'; then
  export PAGER='moar'
else
  export PAGER='less -Fi'
fi
export MANPAGER="${PAGER}"

## history stuff
export HISTCONTROL='ignorespace:ignoredups'
export HISTIGNORE='ls:ll:lla:pwd:bg:fg:history:h'
export HISTSIZE='100000'
export HISTFILESIZE="${HISTSIZE}"
export HISTTIMEFORMAT='%F %T%t'
export HISTFILE="${HOME}/.bash_history"

## less
LESS_TERMCAP_mb=$(tput -T ansi blink) # start blink
LESS_TERMCAP_md=$(tput -T ansi setaf 2 ; tput -T ansi bold) # start bold
LESS_TERMCAP_me=$(tput -T ansi sgr0)  # turn off bold, blink and underline
LESS_TERMCAP_so=$(tput -T ansi smso)  # start standout (reverse video)
LESS_TERMCAP_se=$(tput -T ansi rmso)  # stop standout
LESS_TERMCAP_us=$(tput -T ansi smul)  # start underline
LESS_TERMCAP_ue=$(tput -T ansi rmul)  # stop underline
export LESS_TERMCAP_mb
export LESS_TERMCAP_md
export LESS_TERMCAP_me
export LESS_TERMCAP_se
export LESS_TERMCAP_so
export LESS_TERMCAP_ue
export LESS_TERMCAP_us

# dirs
export SDKMAN_DIR="${HOME}/.sdkman"
export GOPATH="${HOME}/.go"

# files
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/rc"

# misc
export TIMEFORMAT=$'\nreal %3R\tuser %3U\tsys %3S\tpcpu %P\n'
export HIGHLIGHT_OPTIONS='--out-format=ansi --force'
