#!/usr/bin/env bash

## personal
export CODE_DIR="${HOME}/Code"
export WTTR_CITY='Atlanta'

## editor/visual
if executable_exists 'micro'; then
  export EDITOR='micro'
elif executable_exists 'nano'; then
  export EDITOR='nano'
elif executable_exists 'nvim'; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi
export VISUAL="${EDITOR}"

## pager/manpager
if executable_exists 'moar'; then
  export PAGER='moar'
else
  export PAGER='less -Fi'
fi
export MANPAGER="${PAGER}"

## history
export HISTCONTROL='ignorespace:ignoredups'
export HISTIGNORE='ls:ll:lla:pwd:bg:fg:history:h:exit:q:pwd:clear:cls:update:sdf:brc:dl:home:c'
export HISTSIZE='100000'
export HISTFILESIZE="${HISTSIZE}"
export HISTTIMEFORMAT='%F %T%t'
export HISTFILE="${XDG_STATE_HOME}/bash/history"

## less
LESS_TERMCAP_mb=$(tput -T ansi blink) # start blink
LESS_TERMCAP_md=$(tput -T ansi setaf 2 ; tput -T ansi bold) # start bold
LESS_TERMCAP_me=$(tput -T ansi sgr0)  # turn off bold, blink and underline
LESS_TERMCAP_so=$(tput -T ansi smso)  # start standout (reverse video)
LESS_TERMCAP_se=$(tput -T ansi rmso)  # stop standout
LESS_TERMCAP_us=$(tput -T ansi smul)  # start underline
LESS_TERMCAP_ue=$(tput -T ansi rmul)  # stop underline
export LESS_TERMCAP_mb
export LESS_TERMCAP_md
export LESS_TERMCAP_me
export LESS_TERMCAP_se
export LESS_TERMCAP_so
export LESS_TERMCAP_ue
export LESS_TERMCAP_us

## dirs and files
export ANDROID_HOME="${XDG_DATA_HOME}/android"
export ATOM_HOME="${XDG_DATA_HOME}/atom"
export AWS_CONFIG_FILE="${XDG_CONFIG_HOME}/aws/config"
export AWS_SHARED_CREDENTIALS_FILE="${XDG_CONFIG_HOME}/aws/credentials"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
export FFMPEG_DATADIR="${XDG_CONFIG_HOME}/ffmpeg"
export GEM_HOME="${XDG_DATA_HOME}/gem"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export GOBIN="${HOME}/.go/bin"
export GOCACHE="${XDG_CACHE_HOME}/go-build"
export GOMODCACHE="${XDG_CACHE_HOME}/go/mod"
export GOPATH="${HOME}/.go"
export GRADLE_USER_HOME="${XDG_DATA_HOME}/gradle"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"
export INPUTRC="${XDG_CONFIG_HOME}/readline/inputrc"
export KDEHOME="${XDG_CONFIG_HOME}/kde"
export LESSHISTFILE="${XDG_STATE_HOME}/less/history"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
export PARALLEL_HOME="${XDG_CONFIG_HOME}/parallel"
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/config"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export SDKMAN_DIR="${XDG_DATA_HOME}/sdkman"
export SCREENRC="${XDG_CONFIG_HOME}/screen/screenrc"
export STACK_ROOT="${XDG_DATA_HOME}/stack"
export STARSHIP_CACHE="$XDG_CACHE_HOME"/starship
export TERMINFO="${XDG_DATA_HOME}/terminfo"
export TERMINFO_DIRS="${XDG_DATA_HOME}/terminfo:/usr/share/terminfo"
export WGETRC="${XDG_CONFIG_HOME}/wgetrc"

## misc
export HSTR_CONFIG='hicolor'
export SYSTEMD_PAGER=''
export TIMEFORMAT=$'\nreal %3R\tuser %3U\tsys %3S\tpcpu %P\n'
