#!/usr/bin/env bash

# https://unix.stackexchange.com/questions/9123/is-there-a-one-liner-that-allows-me-to-create-a-directory-and-move-into-it-at-th/9124#9124
function mkcd() {
  if [[ "$#" -ne 1 ]]; then
    echo "${0##*/}: Expected exactly 1 argument" >&2
    exit 2
  fi
  case "$1" in
    */.. | */../) cd -- "$1" ;; # that doesn't make any sense unless the directory already exists
    /*/../*) (cd "${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd -- "$1" ;;
    /*) mkdir -p "$1" && cd "$1" ;;
    */../*) (cd "./${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd "./$1" ;;
    ../*) (cd .. && mkdir -p "${1#.}") && cd "$1" ;;
    *) mkdir -p "./$1" && cd "./$1" ;;
  esac
}

function fff() {
  command fff "$@"
  cd "$(cat "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d")" || exit
}

function functions() {
  typeset -F | cut --delimiter=' ' --fields=3 | while read func; do
    (
      shopt -s extdebug
      declare -F "${func}"
    ) | awk '{ print $1, $3":"$2 }'
  done |
    sed "s#${HOME}#~#g" |
    column --table --table-columns 'FUNCTION,SOURCE' --table-truncate 1
}

function aliases() {
  PS4='+$BASH_SOURCE ' BASH_XTRACEFD=7 bash -xic ':' 7> >(
    grep --perl-regexp '^\++\S+ alias ' |
      sed 's/^\+*//' |
      sed --regexp-extended "s#([^\])'#\1#g" |
      awk -F' alias ' -v OFS='‽' '{ print $2, $1 }' |
      LC_COLLATE=C sort
  ) |
    sed "s#${HOME}#~#g" |
    column --separator '‽' --table --table-columns 'ALIAS,SOURCE' --table-columns-limit 2 --table-truncate 1
}

function executable_exists() {
  # executables / no builtins, aliases, or functions
  type -aPf "$1" >/dev/null 2>&1
}

function command_exists() {
  # executables and builtins / no aliases or functions
  type -Pf "$1" >/dev/null 2>&1
}

function path_remove() {
  PATH=$(echo -n "$PATH" | awk -v RS=: -v ORS=: '$0 != "'"$1"'"' | sed 's/:$//')
}

function path_append() {
  path_remove "$1"
  PATH="$PATH:$1"
}

function path_prepend() {
  path_remove "$1"
  PATH="$1:$PATH"
}
