#!/usr/bin/env bash

# https://unix.stackexchange.com/questions/9123/is-there-a-one-liner-that-allows-me-to-create-a-directory-and-move-into-it-at-th/9124#9124
function mkcd() {
  case "$1" in
    */.. | */../) cd -- "$1" ;; # that doesn't make any sense unless the directory already exists
    /*/../*) (cd "${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd -- "$1" ;;
    /*) mkdir -p "$1" && cd "$1" ;;
    */../*) (cd "./${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd "./$1" ;;
    ../*) (cd .. && mkdir -p "${1#.}") && cd "$1" ;;
    *) mkdir -p "./$1" && cd "./$1" ;;
  esac
}

function fff() {
  command fff "$@"
  cd "$(cat "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d")" || exit
}

#function executable_exists() {
#  # executables / no builtins, aliases, or functions
#  type -aPf "$1" >/dev/null 2>&1
#}
#
#function command_exists() {
#  # executables and builtins / no aliases or functions
#  type -Pf "$1" >/dev/null 2>&1
#}
#
#function path_remove () {
#  PATH=$(echo -n "$PATH" | awk -v RS=: -v ORS=: '$0 != "'"$1"'"' | sed 's/:$//')
#}
#
#function path_append () {
#  path_remove "$1"
#  PATH="$PATH:$1"
#}
#
#function path_prepend () {
#  path_remove "$1"
#  PATH="$1:$PATH"
#}
