#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

umask 022
ulimit -S -c 0 # no core dumps
set -o notify
set -o noclobber
set -o ignoreeof
unalias -a

# shopt -p | sort -k3
shopt -u assoc_expand_once
shopt -s autocd
shopt -u cdable_vars
shopt -s cdspell
shopt -s checkhash
shopt -s checkjobs
shopt -s checkwinsize
shopt -s cmdhist
shopt -u compat31
shopt -u compat32
shopt -u compat40
shopt -u compat41
shopt -u compat42
shopt -u compat43
shopt -u compat44
shopt -s complete_fullquote
shopt -s direxpand
shopt -s dirspell
shopt -s dotglob
shopt -u execfail
shopt -s expand_aliases
shopt -u extdebug
shopt -s extglob
shopt -s extquote
shopt -u failglob
shopt -s force_fignore
shopt -s globasciiranges
shopt -s globstar
shopt -u gnu_errfmt
shopt -s histappend
shopt -u histreedit
shopt -u histverify
shopt -u hostcomplete
shopt -u huponexit
shopt -u inherit_errexit
shopt -s interactive_comments
shopt -u lastpipe
shopt -u lithist
shopt -u localvar_inherit
shopt -u localvar_unset
shopt -u login_shell
shopt -u mailwarn
shopt -s nocaseglob
shopt -u nocasematch
shopt -s no_empty_cmd_completion
shopt -u nullglob
shopt -s progcomp
shopt -s progcomp_alias
shopt -s promptvars
shopt -u restricted_shell
shopt -u shift_verbose
shopt -s sourcepath
shopt -u xpg_echo

# source function and exports first so they can be used immediately
if [[ -f "${XDG_CONFIG_HOME}/bash/functions" && -r "${XDG_CONFIG_HOME}/bash/functions" ]]; then
  source "${XDG_CONFIG_HOME}/bash/functions"
fi
if [[ -f "${XDG_CONFIG_HOME}/bash/exports" && -r "${XDG_CONFIG_HOME}/bash/exports" ]]; then
  source "${XDG_CONFIG_HOME}/bash/exports"
fi

# Arch Box Sourcing
# /etc/profile
#   /etc/profile.d/*.sh (bunch of program-specific stuff, like autojump, safe-rm, snap, etc.)
#   /etc/bash.bashrc
#     /usr/share/bash-completion/bash_completion
#       /etc/bash_completion.d/*
#       ~/.bash_completion

## files to source
for file in \
  '/usr/share/fzf/key-bindings.bash' \
  '/usr/share/fzf/completion.bash' \
  '/usr/share/git/completion/git-completion.bash' \
  '/usr/share/doc/pkgfile/command-not-found.bash' \
  "${SDKMAN_DIR}/bin/sdkman-init.sh" \
  "${XDG_CONFIG_HOME}/broot/launcher/bash/br" \
  "${XDG_CONFIG_HOME}/bash/aliases" \
  "${XDG_CONFIG_HOME}/bash/local"; do
  if is_readable_file "${file}"; then
    source "${file}"
  fi
done
unset -v file

## dirs to put on path
for dir in \
  "$(if executable_exists 'ruby'; then echo "$(ruby -e 'puts Gem.user_dir')/bin"; else echo ''; fi)" \
  "$(if executable_exists 'go'; then echo "$(go env GOPATH)/bin"; else echo ''; fi)" \
  "$(if [[ -n "${CARGO_HOME}" ]]; then echo "${CARGO_HOME}/bin"; else echo ''; fi)" \
  "${HOME}/.bin/other" \
  "${HOME}/.bin"; do
  if [[ -n "${dir}" && -d "${dir}" ]]; then
    path_prepend "${dir}"
  fi
done
unset -v dir

## misc init stuff
is_readable_file "${XDG_CONFIG_HOME}/dircolors" && eval "$(dircolors "${XDG_CONFIG_HOME}/dircolors")"
executable_exists 'zoxide' && eval "$(zoxide init bash)"
executable_exists 'starship' && eval "$(starship init bash)"
executable_exists 'aws_completer' && complete -C 'aws_completer' aws
